import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "privacy ... gen connect",
  description:
    "how gen connect handles your data: what we collect, who processes it, and how to delete it. plain language, no dark patterns.",
};

const SECTIONS = [
  {
    title: "the short version",
    body: "gen connect exists to draft outreach in your voice and put it in front of the right people. we collect what that requires and nothing more. we don't sell your data, we don't train public models on your writing, and you can leave with your data or have it deleted whenever you want.",
  },
  {
    title: "your account ... supabase",
    body: "sign-in is magic-link email through supabase auth. no passwords stored, ever. we keep your email address and basic account metadata so you can log in and we can reach you about your account.",
  },
  {
    title: "billing ... stripe",
    body: "payments run through stripe. we never see or store your card number ... stripe holds that. we keep your stripe customer id, plan, and subscription status so entitlements work.",
  },
  {
    title: "sending ... resend",
    body: "outbound email is delivered through resend, using sending identities you connect and approve. message content and delivery events pass through resend's infrastructure to reach the inbox.",
  },
  {
    title: "lead and contact data ... you're the controller",
    body: "the leads and contacts in gen connect are imported by you or sourced for your account. for that data, you are the controller and gen connect is the processor ... we store and process it only to run the product for you: enrichment, drafting, sending, and the unibox. you're responsible for having a lawful basis to contact the people you import, and for honoring opt-outs.",
  },
  {
    title: "ai drafting ... anthropic and deepseek",
    body: "drafts are generated by models from anthropic (claude) and deepseek. to draft, we send the model the context it needs: your voice samples, the lead's details, and the thread history. we use these providers under their api terms ... your content is not used to train their public models.",
  },
  {
    title: "your voice samples",
    body: "the writing samples you give gen are how drafts end up sounding like you. they're stored per-account, used only to draft for you, and scrubbed when you delete them or your account.",
  },
  {
    title: "delete your data",
    body: "there's no self-serve delete button yet (we're building one). until then, deletion requests are honored by email within 30 days. write to privacy@lunari.pro from your account email with the subject \"delete my data\" and we'll remove your account, voice samples, leads, threads, and drafts, and confirm when it's done. exports before deletion are available on request too.",
  },
  {
    title: "questions",
    body: "anything unclear, anything you want changed, anything you want to see ... email privacy@lunari.pro. a human reads it.",
  },
] as const;

export default function PrivacyPage() {
  return (
    <main className="lunari-canvas relative min-h-screen overflow-hidden">
      <div
        className="pointer-events-none absolute inset-0"
        style={{
          background:
            "radial-gradient(42% 40% at 50% 18%, var(--gen-accent-soft) 0%, transparent 70%)",
        }}
      />

      <div className="relative z-10 mx-auto max-w-2xl px-6 py-20">
        <Link
          href="/"
          className="font-mono text-[11px] uppercase tracking-[0.22em] text-lunari-neutral-500 transition-colors hover:text-lunari-cream"
        >
          ← gen connect
        </Link>

        <h1
          className="mt-8 text-4xl tracking-tight text-lunari-cream"
          style={{ fontFamily: "var(--font-cinzel)" }}
        >
          privacy
        </h1>
        <div className="mt-6 h-px w-24 bg-gradient-to-r from-transparent via-lunari-gold to-transparent opacity-70" />
        <p className="mt-6 text-sm leading-relaxed text-lunari-neutral-400">
          plain language, no dark patterns. last updated july 2026.
        </p>

        <div className="mt-12 space-y-10">
          {SECTIONS.map((s) => (
            <section key={s.title}>
              <h2 className="text-lg font-medium text-lunari-cream">
                {s.title}
              </h2>
              <p className="mt-3 text-sm leading-relaxed text-lunari-neutral-400">
                {s.body}
              </p>
            </section>
          ))}
        </div>

        <footer className="mt-16 border-t border-lunari-surface-elevated pt-8 text-center font-mono text-[11px] text-lunari-neutral-500">
          © {new Date().getFullYear()} lunari titans ·{" "}
          <Link href="/terms" className="hover:text-lunari-cream">
            terms
          </Link>
        </footer>
      </div>
    </main>
  );
}
